#!/bin/zsh
PROJECTS_DIR="$HOME/projects"

target="$PROJECTS_DIR/$1"

echo "Creating new project $1 in $target"

mkdir $target

cd $target

echo "directory created, initializing git"

echo "$1" >> README.md
echo "==============" >> README.md

git init

git add README.md

git commit -m "Initialize repo"
